### PR TITLE
Using lerp for relatively smooth tracking

### PR DESCRIPTION
**Pull request by frederik-markus**
Renamed some stuff to make them more general.

### CODE REVIEW

**Comment by frederik-markus** [comment]
@li-yunwen Has using the queue improved performance?

**Comment by li-yunwen** [comment]
> @li-yunwen Has using the queue improved performance?

It's really hard to say, but theoretically all our operations are doable by `Queue` in O(1). But `List` does some of them like `Insert/Remove` in O(n), so that's why I changed it to `Queue`.

I issued a new pull request with what I assume a really clearer and better updating flow. If in any update frame, there's no lerping forward, I add a warning message to Log. However, I can run the game (after a stuck at the beginning) with above 60FPS (frame rate per sec) without any single warning. Therefore I'm thinking, is the acceleration/deacceleration from us or from the driver/sensor.

So I plot the `speed=distance/time_interval` calculated from openF1 datapoints. This car speed should be the same or similar to our algorithm because we are using linear interpolation between points. This what I got:
speed_curve_1_cycle

You can see some big speed changes between consecutive segments, Idk if this is actually causing the phenomena.

**Comment by frederik-markus** [comment]
Can we maybe include some smoothing? Something that limits the gradient so it cannot jolt too much? It seems to be like the underlying data can be mapped quite nicely but the jolting leads to extreme spikes.

**Comment by li-yunwen** [comment]
> Can we maybe include some smoothing? Something that limits the gradient so it cannot jolt too much? It seems to be like the underlying data can be mapped quite nicely but the jolting leads to extreme spikes.

Does smoothing mean not staying true to the given position points? If that's the case, I doubt the feasibility, especially in real time.

**Comment by li-yunwen** [comment]
> Can we maybe include some smoothing? Something that limits the gradient so it cannot jolt too much? It seems to be like the underlying data can be mapped quite nicely but the jolting leads to extreme spikes.

If the problem lies in the original data, then I think it needs to be solved on the data side, not the game. I guess an intuitive practice is to have some other program that constantly fetch the data, do some filtering, then publish it to some database. Then our game can subscribe to this database instead, so it gets clean position data. Though, I think this would be less related to VR.

**Comment by frederik-markus** [comment]
@li-yunwen Can this be merged?

**Comment by li-yunwen** [comment]
> @li-yunwen Can this be merged?

I think we don't have anything new in this pull request? Maybe just close it?

**Pull request closed without merging**
